import type { DishExplanation } from "@/lib/dish/types";

/**
 * The dishes this build knows without a model.
 *
 * A published page cannot reach any server, so the demo carries its answers
 * with it. They are written to the same rule the real prompt is held to: only
 * "usually" or "sometimes", never "contains", and `from` names the part of the
 * dish a diner can point at and ask about.
 *
 * Anything not in here comes back with `recognised: false`, which is not a
 * failure mode invented for the demo — it is exactly what the real app does
 * with a dish the model does not know, and the screens already say "not known"
 * rather than showing a green tick.
 */

export interface DemoDish extends DishExplanation {
  /** Spellings and short forms people actually type. Diacritics are folded. */
  aliases: string[];
}

export const DISHES: DemoDish[] = [
  /* ---- Vietnam --------------------------------------------------------- */
  {
    printedName: "Bún chả",
    englishName: "Grilled pork with noodles",
    aliases: ["bun cha", "hanoi pork noodles"],
    oneLine:
      "Charcoal-grilled pork in a bowl of sweet-sour broth, with cold rice noodles and herbs alongside.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "mild",
    recognised: true,
    likelyAllergens: [
      { key: "fish", likelihood: "usually", from: "the fish sauce in the broth" },
      { key: "peanuts", likelihood: "sometimes", from: "crushed peanuts scattered on top" },
      { key: "soy", likelihood: "sometimes", from: "the dipping sauce" },
    ],
    whatItIs:
      "Pork patties and slices of belly, grilled over charcoal until the edges char, then dropped into a bowl of warm sweet-and-sour broth. Cold rice noodles, lettuce and a pile of herbs come on separate plates. You build each mouthful yourself.",
    tastesLike: "Smoky and a bit sweet, with a sour edge from vinegar and a hit of garlic.",
    origin: "Hanoi, northern Vietnam",
    madeWith: ["pork", "rice noodles", "fish sauce", "sugar", "vinegar", "herbs"],
    servedAs: "a bowl with plates alongside",
  },
  {
    printedName: "Phở bò",
    englishName: "Beef noodle soup",
    aliases: ["pho", "pho bo", "beef pho", "vietnamese noodle soup"],
    oneLine: "A deep beef broth over flat rice noodles, with thin slices of beef and a plate of herbs.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "fish", likelihood: "usually", from: "the fish sauce the broth is seasoned with" },
      { key: "soy", likelihood: "sometimes", from: "the hoisin sauce put on the table" },
      { key: "gluten", likelihood: "sometimes", from: "the hoisin sauce, which often has wheat in it" },
    ],
    whatItIs:
      "Beef bones simmered for hours with charred ginger, onion and star anise, then strained clear and poured boiling over flat rice noodles and raw beef, which cooks in the bowl. Herbs, lime and chilli come on the side to add yourself.",
    tastesLike: "Clean and beefy with a warm, sweet spice behind it. Not hot unless you make it hot.",
    origin: "northern Vietnam",
    madeWith: ["beef bones", "rice noodles", "star anise", "ginger", "fish sauce", "herbs"],
    servedAs: "a large bowl with a plate of herbs",
  },
  {
    printedName: "Gỏi cuốn",
    englishName: "Fresh spring rolls",
    aliases: ["goi cuon", "summer rolls", "fresh spring rolls", "rice paper rolls"],
    oneLine: "Cold rice-paper rolls with prawn, pork and mint, dipped in peanut sauce.",
    priceText: "",
    course: "starters",
    dietary: "meat",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "peanuts", likelihood: "usually", from: "the dipping sauce" },
      { key: "shellfish", likelihood: "usually", from: "the prawn inside" },
      { key: "fish", likelihood: "usually", from: "the fish sauce in the dip" },
      { key: "soy", likelihood: "sometimes", from: "the hoisin in the dipping sauce" },
    ],
    whatItIs:
      "Rice paper soaked soft and rolled cold around a whole prawn, a slice of boiled pork, rice vermicelli, lettuce and a lot of mint. Nothing is cooked once it is rolled. A thick brown peanut sauce comes with it.",
    tastesLike: "Cool, plain and herby, until the sauce makes it sweet and salty.",
    origin: "southern Vietnam",
    madeWith: ["rice paper", "prawn", "pork", "rice vermicelli", "mint", "peanut sauce"],
    servedAs: "four or five rolls with a bowl of sauce",
  },
  {
    printedName: "Bánh mì",
    englishName: "Vietnamese baguette",
    aliases: ["banh mi", "vietnamese sandwich"],
    oneLine: "A crisp baguette split and filled with pork, pâté, pickled carrot and coriander.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "mild",
    recognised: true,
    likelyAllergens: [
      { key: "gluten", likelihood: "usually", from: "the baguette" },
      { key: "eggs", likelihood: "usually", from: "the mayonnaise" },
      { key: "soy", likelihood: "sometimes", from: "the seasoning on the meat" },
      { key: "fish", likelihood: "sometimes", from: "the fish sauce in the marinade" },
    ],
    whatItIs:
      "A light baguette, crisp outside and hollow inside, spread with pâté and mayonnaise, then filled with grilled pork or cold cuts, pickled carrot and daikon, cucumber, coriander and chilli.",
    tastesLike: "Crunchy, rich and sharp all at once. The pickles cut through the fat.",
    origin: "Vietnam, out of French bread",
    madeWith: ["baguette", "pork", "pâté", "pickled carrot", "coriander", "chilli"],
    servedAs: "one sandwich in paper",
  },

  /* ---- Thailand -------------------------------------------------------- */
  {
    printedName: "ผัดไทย",
    englishName: "Pad thai",
    aliases: ["pad thai", "phat thai", "padthai"],
    oneLine: "Rice noodles fried with egg, tamarind and fish sauce, with peanuts on top.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "mild",
    recognised: true,
    likelyAllergens: [
      { key: "peanuts", likelihood: "usually", from: "the crushed peanuts scattered over it" },
      { key: "eggs", likelihood: "usually", from: "the egg fried through the noodles" },
      { key: "fish", likelihood: "usually", from: "the fish sauce in the seasoning" },
      { key: "shellfish", likelihood: "sometimes", from: "the dried shrimp in the sauce" },
      { key: "soy", likelihood: "sometimes", from: "the soy sauce" },
    ],
    whatItIs:
      "Flat rice noodles fried hard and fast with egg, tofu, dried shrimp and a sauce of tamarind, palm sugar and fish sauce. Bean sprouts and garlic chives go in at the end, and crushed peanuts, chilli powder and a lime wedge come on top.",
    tastesLike: "Sweet, sour and salty together, with a smoky edge from the hot pan.",
    origin: "Thailand",
    madeWith: ["rice noodles", "egg", "tamarind", "fish sauce", "peanuts", "bean sprouts"],
    servedAs: "a plate with a lime wedge",
  },
  {
    printedName: "ต้มยำกุ้ง",
    englishName: "Tom yum goong",
    aliases: ["tom yum", "tom yum goong", "tom yam", "hot and sour prawn soup"],
    oneLine: "A hot-and-sour prawn soup sharp with lemongrass, lime leaf and chilli.",
    priceText: "",
    course: "starters",
    dietary: "fish",
    spice: "hot",
    recognised: true,
    likelyAllergens: [
      { key: "shellfish", likelihood: "usually", from: "the prawns" },
      { key: "fish", likelihood: "usually", from: "the fish sauce" },
      { key: "dairy", likelihood: "sometimes", from: "the evaporated milk in the creamy version" },
    ],
    whatItIs:
      "A thin, fierce broth built on lemongrass, galangal, kaffir lime leaf, lime juice, fish sauce and chilli, with prawns and mushrooms cooked in it. Some kitchens stir in evaporated milk, which turns it cloudy and softer.",
    tastesLike: "Very sour, very hot, and deeply fragrant. It clears your head.",
    origin: "central Thailand",
    madeWith: ["prawns", "lemongrass", "galangal", "lime leaf", "chilli", "fish sauce"],
    servedAs: "a bowl, shared, with rice",
  },
  {
    printedName: "ส้มตำ",
    englishName: "Green papaya salad",
    aliases: ["som tam", "som tum", "papaya salad"],
    oneLine: "Shredded unripe papaya pounded with lime, chilli, fish sauce and peanuts.",
    priceText: "",
    course: "starters",
    dietary: "fish",
    spice: "hot",
    recognised: true,
    likelyAllergens: [
      { key: "peanuts", likelihood: "usually", from: "the peanuts pounded through it" },
      { key: "fish", likelihood: "usually", from: "the fish sauce" },
      { key: "shellfish", likelihood: "usually", from: "the dried shrimp" },
    ],
    whatItIs:
      "Green papaya shredded into threads and bruised in a clay mortar with garlic, chilli, long beans, tomato, dried shrimp, peanuts, lime and fish sauce. Pounding, not mixing, is the point: it drives the dressing into the fruit.",
    tastesLike: "Crunchy, sour and hot, with a salty, funky depth underneath.",
    origin: "Isan, north-eastern Thailand",
    madeWith: ["green papaya", "lime", "chilli", "fish sauce", "peanuts", "dried shrimp"],
    servedAs: "a plate, usually with sticky rice",
  },
  {
    printedName: "แกงเขียวหวาน",
    englishName: "Green curry",
    aliases: ["green curry", "gaeng keow wan", "kaeng khiao wan", "thai green curry"],
    oneLine: "Coconut curry, green from fresh chillies, with chicken and Thai basil.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "medium",
    recognised: true,
    likelyAllergens: [
      { key: "fish", likelihood: "usually", from: "the fish sauce and the shrimp paste in the curry paste" },
      { key: "shellfish", likelihood: "usually", from: "the shrimp paste in the curry paste" },
    ],
    whatItIs:
      "A paste of green chilli, lemongrass, galangal and shrimp paste fried in coconut cream until it splits, then loosened with coconut milk and simmered with chicken, pea aubergines and Thai basil.",
    tastesLike: "Sweet and creamy first, then the heat arrives and stays.",
    origin: "central Thailand",
    madeWith: ["coconut milk", "green chilli", "lemongrass", "chicken", "thai basil", "fish sauce"],
    servedAs: "a bowl with a plate of rice",
  },

  /* ---- Japan ----------------------------------------------------------- */
  {
    printedName: "ラーメン",
    englishName: "Ramen",
    aliases: ["ramen", "tonkotsu ramen", "shoyu ramen"],
    oneLine: "Wheat noodles in a long-simmered broth, with pork, egg and spring onion.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "gluten", likelihood: "usually", from: "the wheat noodles" },
      { key: "soy", likelihood: "usually", from: "the soy-based seasoning in the broth" },
      { key: "eggs", likelihood: "usually", from: "the marinated egg, and often the noodles" },
      { key: "fish", likelihood: "usually", from: "the dashi that most broths are built on" },
      { key: "sesame", likelihood: "sometimes", from: "the oil or seeds finished over the top" },
    ],
    whatItIs:
      "Springy wheat noodles in a bowl of broth — pork bone, chicken, or a fish-and-kelp dashi — seasoned with a salty base called tare. Sliced pork belly, a soft-yolk marinated egg, bamboo shoots and spring onion go on top.",
    tastesLike: "Deeply savoury and a bit fatty, with the noodles firm in the middle.",
    origin: "Japan, out of Chinese wheat noodles",
    madeWith: ["wheat noodles", "pork", "soy sauce", "dashi", "egg", "spring onion"],
    servedAs: "one large bowl, eaten fast",
  },
  {
    printedName: "寿司",
    englishName: "Sushi",
    aliases: ["sushi", "nigiri", "maki"],
    oneLine: "Vinegared rice with raw fish on top or rolled inside seaweed.",
    priceText: "",
    course: "mains",
    dietary: "fish",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "fish", likelihood: "usually", from: "the raw fish on top" },
      { key: "soy", likelihood: "usually", from: "the soy sauce you dip it in" },
      { key: "gluten", likelihood: "usually", from: "the soy sauce, which is brewed with wheat" },
      { key: "shellfish", likelihood: "sometimes", from: "the prawn, crab or scallop pieces" },
      { key: "sesame", likelihood: "sometimes", from: "the seeds on rolls" },
      { key: "eggs", likelihood: "sometimes", from: "the sweet omelette piece, and the mayonnaise in some rolls" },
    ],
    whatItIs:
      "Rice seasoned with vinegar, sugar and salt, pressed by hand into small blocks with a slice of raw fish laid over, or rolled in a sheet of dried seaweed. Wasabi, pickled ginger and soy sauce come with it.",
    tastesLike: "Cool, faintly sweet rice against clean, soft fish.",
    origin: "Japan",
    madeWith: ["rice", "rice vinegar", "raw fish", "nori", "wasabi", "soy sauce"],
    servedAs: "pieces on a board or plate",
  },
  {
    printedName: "とんかつ",
    englishName: "Tonkatsu",
    aliases: ["tonkatsu", "pork katsu", "katsu"],
    oneLine: "A thick pork cutlet in crisp breadcrumbs, sliced, with a dark sweet sauce.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "gluten", likelihood: "usually", from: "the panko breadcrumbs and the flour it is dusted in" },
      { key: "eggs", likelihood: "usually", from: "the egg wash under the crumbs" },
      { key: "soy", likelihood: "usually", from: "the tonkatsu sauce" },
      { key: "sesame", likelihood: "sometimes", from: "the seeds ground at the table into the sauce" },
    ],
    whatItIs:
      "A thick pork loin or fillet dusted in flour, dipped in egg, pressed into coarse panko crumbs and deep-fried, then cut into strips so you can pick it up with chopsticks. Shredded raw cabbage, rice and miso soup come with it.",
    tastesLike: "Very crunchy outside, plain and juicy inside. The sauce is sweet and tangy, like fruity brown sauce.",
    origin: "Japan",
    madeWith: ["pork loin", "panko", "egg", "flour", "cabbage", "tonkatsu sauce"],
    servedAs: "a set with rice, soup and cabbage",
  },
  {
    printedName: "お好み焼き",
    englishName: "Okonomiyaki",
    aliases: ["okonomiyaki", "japanese savoury pancake"],
    oneLine: "A thick cabbage pancake griddled flat, painted with sauce and mayonnaise.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "gluten", likelihood: "usually", from: "the flour in the batter" },
      { key: "eggs", likelihood: "usually", from: "the batter and the mayonnaise" },
      { key: "fish", likelihood: "usually", from: "the dashi in the batter and the bonito flakes on top" },
      { key: "soy", likelihood: "usually", from: "the sauce brushed over it" },
      { key: "molluscs", likelihood: "sometimes", from: "the squid, in the seafood version" },
      { key: "shellfish", likelihood: "sometimes", from: "the prawn, in the seafood version" },
    ],
    whatItIs:
      "A loose batter of flour, egg and dashi packed with shredded cabbage, cooked slowly on a hot plate with pork belly laid over the top, then flipped. Finished with a sweet brown sauce, mayonnaise, seaweed powder and bonito flakes that move in the heat.",
    tastesLike: "Soft and sweet from the cabbage, salty and rich on top.",
    origin: "Osaka and Hiroshima",
    madeWith: ["cabbage", "flour", "egg", "dashi", "pork belly", "okonomi sauce"],
    servedAs: "one pancake, cut at the table",
  },

  /* ---- Korea ----------------------------------------------------------- */
  {
    printedName: "비빔밥",
    englishName: "Bibimbap",
    aliases: ["bibimbap", "bibimbop", "mixed rice"],
    oneLine: "Rice under neat piles of vegetables and an egg, mixed together with chilli paste.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "medium",
    recognised: true,
    likelyAllergens: [
      { key: "eggs", likelihood: "usually", from: "the fried egg on top" },
      { key: "sesame", likelihood: "usually", from: "the sesame oil and seeds through the vegetables" },
      { key: "soy", likelihood: "usually", from: "the soy sauce the vegetables are seasoned with" },
      { key: "gluten", likelihood: "sometimes", from: "the gochujang, which is often made with wheat" },
    ],
    whatItIs:
      "A bowl of rice with seasoned vegetables arranged in separate piles on top — spinach, bean sprouts, carrot, mushroom, courgette — plus beef and a fried egg. A spoon of red chilli paste goes on, and you mix the whole thing hard before eating.",
    tastesLike: "Nutty and savoury, with a gentle chilli warmth. Every mouthful is slightly different.",
    origin: "Korea",
    madeWith: ["rice", "gochujang", "sesame oil", "spinach", "beef", "egg"],
    servedAs: "one bowl, sometimes a sizzling stone one",
  },
  {
    printedName: "떡볶이",
    englishName: "Tteokbokki",
    aliases: ["tteokbokki", "topokki", "ddeokbokki", "rice cakes"],
    oneLine: "Chewy rice sticks in a thick, sweet, fiery red sauce.",
    priceText: "",
    course: "starters",
    dietary: "fish",
    spice: "hot",
    recognised: true,
    likelyAllergens: [
      { key: "fish", likelihood: "usually", from: "the fish cakes and the anchovy stock" },
      { key: "gluten", likelihood: "usually", from: "the fish cakes and the gochujang" },
      { key: "soy", likelihood: "usually", from: "the seasoning" },
      { key: "eggs", likelihood: "sometimes", from: "the boiled egg added on top" },
      { key: "sesame", likelihood: "sometimes", from: "the seeds scattered over" },
    ],
    whatItIs:
      "Cylinders of pressed rice cake simmered in anchovy stock with gochujang, sugar and chilli flakes until the sauce goes thick and glossy, with sheets of fish cake and spring onion through it.",
    tastesLike: "Very chewy, sweet at the front and hot at the back.",
    origin: "Korea, sold on the street",
    madeWith: ["rice cakes", "gochujang", "fish cake", "anchovy stock", "sugar", "spring onion"],
    servedAs: "a shared pan or a paper cup",
  },

  /* ---- China ----------------------------------------------------------- */
  {
    printedName: "麻婆豆腐",
    englishName: "Mapo tofu",
    aliases: ["mapo tofu", "ma po tofu", "mapo doufu"],
    oneLine: "Soft tofu in a red, numbing sauce with minced pork and Sichuan pepper.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "hot",
    recognised: true,
    likelyAllergens: [
      { key: "soy", likelihood: "usually", from: "the tofu and the fermented bean paste" },
      { key: "gluten", likelihood: "usually", from: "the fermented broad bean paste, which is made with wheat flour" },
    ],
    whatItIs:
      "Cubes of soft tofu slipped into a sauce of fermented broad bean paste, fermented black beans, chilli and minced pork, thickened lightly and finished with ground Sichuan pepper.",
    tastesLike: "Savoury and hot, with a strange tingling numbness on your lips from the pepper.",
    origin: "Chengdu, Sichuan",
    madeWith: ["tofu", "doubanjiang", "minced pork", "sichuan pepper", "chilli", "spring onion"],
    servedAs: "a bowl to share, with rice",
  },
  {
    printedName: "宫保鸡丁",
    englishName: "Kung pao chicken",
    aliases: ["kung pao chicken", "gong bao chicken", "kung po"],
    oneLine: "Diced chicken fried with dried chillies and peanuts in a sweet-sour sauce.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "medium",
    recognised: true,
    likelyAllergens: [
      { key: "peanuts", likelihood: "usually", from: "the peanuts fried through it" },
      { key: "soy", likelihood: "usually", from: "the soy sauce in the glaze" },
      { key: "gluten", likelihood: "usually", from: "the soy sauce and the vinegar" },
      { key: "sesame", likelihood: "sometimes", from: "the sesame oil at the end" },
    ],
    whatItIs:
      "Chicken cut into cubes, marinated and fried hot with whole dried chillies, Sichuan pepper, spring onion and peanuts, then coated in a dark sauce of soy, vinegar and sugar.",
    tastesLike: "Sweet and sour with a slow-building heat, and the peanuts stay crunchy.",
    origin: "Sichuan",
    madeWith: ["chicken", "peanuts", "dried chilli", "soy sauce", "vinegar", "sichuan pepper"],
    servedAs: "a plate to share, with rice",
  },
  {
    printedName: "小笼包",
    englishName: "Soup dumplings",
    aliases: ["xiao long bao", "xiaolongbao", "soup dumplings", "xlb"],
    oneLine: "Thin-skinned dumplings that hold a mouthful of hot soup inside.",
    priceText: "",
    course: "starters",
    dietary: "meat",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "gluten", likelihood: "usually", from: "the wheat wrapper" },
      { key: "soy", likelihood: "usually", from: "the vinegar-and-soy dip" },
      { key: "shellfish", likelihood: "sometimes", from: "the crab, in the crab-and-pork version" },
      { key: "sesame", likelihood: "sometimes", from: "the oil in the dipping sauce" },
    ],
    whatItIs:
      "Minced pork mixed with jellied stock and wrapped in a thin pleated wheat skin. Steaming melts the jelly, so each dumpling arrives full of soup. You bite a small hole first, or it burns you.",
    tastesLike: "Rich and savoury, with the ginger and black vinegar cutting the fat.",
    origin: "Shanghai",
    madeWith: ["pork", "wheat flour", "jellied stock", "ginger", "black vinegar"],
    servedAs: "a steamer basket of eight or ten",
  },

  /* ---- India ----------------------------------------------------------- */
  {
    printedName: "मुर्ग़ मक्खनी",
    englishName: "Butter chicken",
    aliases: ["butter chicken", "murgh makhani", "makhani"],
    oneLine: "Tandoori chicken in a mild, sweet tomato sauce heavy with butter and cream.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "mild",
    recognised: true,
    likelyAllergens: [
      { key: "dairy", likelihood: "usually", from: "the butter and cream in the sauce, and the yoghurt in the marinade" },
      { key: "tree_nuts", likelihood: "sometimes", from: "the cashew paste some kitchens thicken it with" },
    ],
    whatItIs:
      "Chicken marinated in yoghurt and spices, cooked in a tandoor, then finished in a sauce of tomato, butter, cream and warm spice. It is deliberately mild — the sweetness is the point.",
    tastesLike: "Creamy, slightly sweet and gently spiced. Almost no heat.",
    origin: "Delhi",
    madeWith: ["chicken", "tomato", "butter", "cream", "yoghurt", "garam masala"],
    servedAs: "a bowl with naan or rice",
  },
  {
    printedName: "छोले",
    englishName: "Chana masala",
    aliases: ["chana masala", "chole", "chickpea curry"],
    oneLine: "Chickpeas stewed in onion and tomato with tart, dark spice.",
    priceText: "",
    course: "mains",
    dietary: "vegan",
    spice: "medium",
    recognised: true,
    likelyAllergens: [
      { key: "dairy", likelihood: "sometimes", from: "the ghee some kitchens cook it in" },
    ],
    whatItIs:
      "Chickpeas simmered with onion, tomato, ginger and garlic, seasoned with cumin, coriander and amchur or pomegranate seed for sourness, and often darkened with tea or dried gooseberry.",
    tastesLike: "Earthy and tangy, with a warm rather than sharp heat.",
    origin: "northern India and Pakistan",
    madeWith: ["chickpeas", "onion", "tomato", "cumin", "amchur", "ginger"],
    servedAs: "a bowl with bread or rice",
  },
  {
    printedName: "मसाला दोसा",
    englishName: "Masala dosa",
    aliases: ["dosa", "masala dosa", "dhosa"],
    oneLine: "A huge, thin, crisp rice pancake rolled around spiced potato.",
    priceText: "",
    course: "mains",
    dietary: "vegetarian",
    spice: "mild",
    recognised: true,
    likelyAllergens: [
      { key: "dairy", likelihood: "sometimes", from: "the ghee brushed over the pan" },
      { key: "mustard", likelihood: "usually", from: "the mustard seeds popped into the potato filling" },
    ],
    whatItIs:
      "A batter of rice and split lentils, left to ferment overnight, spread paper-thin on a hot griddle until it crisps and lifts, then folded around potato cooked with onion, turmeric and mustard seed. Coconut chutney and a thin lentil soup come with it.",
    tastesLike: "Crisp and faintly sour from the fermenting, with a soft, mild filling.",
    origin: "southern India",
    madeWith: ["rice", "urad dal", "potato", "turmeric", "mustard seed", "curry leaf"],
    servedAs: "one long roll with chutney and sambar",
  },
  {
    printedName: "समोसा",
    englishName: "Samosa",
    aliases: ["samosa", "samosas"],
    oneLine: "A fried pastry triangle filled with spiced potato and peas.",
    priceText: "",
    course: "starters",
    dietary: "vegetarian",
    spice: "mild",
    recognised: true,
    likelyAllergens: [
      { key: "gluten", likelihood: "usually", from: "the wheat pastry" },
    ],
    whatItIs:
      "A stiff wheat pastry folded into a cone, packed with potato, peas, cumin and coriander, sealed and deep-fried until the shell blisters. Tamarind and mint chutneys come alongside.",
    tastesLike: "Crunchy and flaky outside, soft and earthy inside.",
    origin: "north India, by way of Central Asia",
    madeWith: ["wheat flour", "potato", "peas", "cumin", "coriander", "ginger"],
    servedAs: "one or two, with chutney",
  },

  /* ---- Middle East and Turkey ------------------------------------------ */
  {
    printedName: "فلافل",
    englishName: "Falafel",
    aliases: ["falafel", "felafel"],
    oneLine: "Deep-fried balls of crushed chickpeas and herbs, usually in bread with tahini.",
    priceText: "",
    course: "mains",
    dietary: "vegan",
    spice: "mild",
    recognised: true,
    likelyAllergens: [
      { key: "sesame", likelihood: "usually", from: "the tahini sauce, and often the seeds on the outside" },
      { key: "gluten", likelihood: "usually", from: "the pita it is served in" },
    ],
    whatItIs:
      "Dried chickpeas soaked but never cooked, then ground raw with parsley, coriander, garlic and cumin, shaped into balls and deep-fried. The inside stays green and soft while the outside goes dark and crunchy.",
    tastesLike: "Herby and nutty, crunchy then fluffy. The tahini makes it rich.",
    origin: "Egypt and the Levant",
    madeWith: ["chickpeas", "parsley", "coriander", "garlic", "cumin", "tahini"],
    servedAs: "in pita, or a plate of balls with salad",
  },
  {
    printedName: "حُمُّص",
    englishName: "Hummus",
    aliases: ["hummus", "houmous", "hommus"],
    oneLine: "Chickpeas blended smooth with tahini, lemon and garlic.",
    priceText: "",
    course: "starters",
    dietary: "vegan",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "sesame", likelihood: "usually", from: "the tahini it is made with" },
      { key: "gluten", likelihood: "usually", from: "the bread served with it" },
    ],
    whatItIs:
      "Chickpeas cooked until they collapse, then blended with a lot of tahini, lemon juice, garlic and iced water until it goes pale and smooth. Olive oil is poured over the top.",
    tastesLike: "Nutty, sour and very smooth.",
    origin: "the Levant",
    madeWith: ["chickpeas", "tahini", "lemon", "garlic", "olive oil"],
    servedAs: "a shallow bowl with bread",
  },
  {
    printedName: "شاورما",
    englishName: "Shawarma",
    aliases: ["shawarma", "shwarma", "doner", "döner"],
    oneLine: "Meat shaved off a turning vertical spit, wrapped in flatbread with sauce.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "mild",
    recognised: true,
    likelyAllergens: [
      { key: "gluten", likelihood: "usually", from: "the flatbread it is wrapped in" },
      { key: "sesame", likelihood: "usually", from: "the tahini sauce" },
      { key: "dairy", likelihood: "sometimes", from: "the yoghurt sauce, and the yoghurt in the marinade" },
    ],
    whatItIs:
      "Chicken or lamb stacked on a vertical spit and turned against a flame for hours, so the outside crisps and is shaved off in thin strips. It goes into flatbread with pickles, salad and tahini or garlic sauce.",
    tastesLike: "Crisp-edged, spiced and fatty, with sharp pickles cutting it.",
    origin: "the Levant and Turkey",
    madeWith: ["chicken or lamb", "flatbread", "tahini", "pickles", "garlic", "spices"],
    servedAs: "a wrap, or a plate with rice",
  },
  {
    printedName: "Baklava",
    englishName: "",
    aliases: ["baklava", "baklawa"],
    oneLine: "Layers of paper-thin pastry packed with nuts and soaked in syrup.",
    priceText: "",
    course: "desserts",
    dietary: "vegetarian",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "tree_nuts", likelihood: "usually", from: "the pistachios or walnuts between the layers" },
      { key: "gluten", likelihood: "usually", from: "the filo pastry" },
      { key: "dairy", likelihood: "usually", from: "the butter brushed between every sheet" },
    ],
    whatItIs:
      "Dozens of sheets of filo, each brushed with butter, layered around crushed pistachio or walnut, baked until gold, then drenched in sugar syrup while still hot so it soaks all the way through.",
    tastesLike: "Extremely sweet, buttery and crunchy, with the nuts keeping it from being sickly.",
    origin: "Turkey and the eastern Mediterranean",
    madeWith: ["filo pastry", "pistachios", "butter", "sugar syrup", "lemon"],
    servedAs: "one or two small pieces",
  },

  /* ---- Europe ---------------------------------------------------------- */
  {
    printedName: "Moussaka",
    englishName: "",
    aliases: ["moussaka", "mousaka"],
    oneLine: "Layers of aubergine and spiced lamb under a thick baked white sauce.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "mild",
    recognised: true,
    likelyAllergens: [
      { key: "dairy", likelihood: "usually", from: "the béchamel on top and the cheese in it" },
      { key: "gluten", likelihood: "usually", from: "the flour the béchamel is thickened with" },
      { key: "eggs", likelihood: "sometimes", from: "the egg beaten into the béchamel" },
    ],
    whatItIs:
      "Slices of aubergine fried or roasted, layered with minced lamb cooked in tomato, cinnamon and oregano, topped with a thick béchamel and baked until the top browns and sets.",
    tastesLike: "Rich and savoury with a warm sweetness from the cinnamon.",
    origin: "Greece",
    madeWith: ["aubergine", "lamb", "tomato", "béchamel", "cinnamon", "cheese"],
    servedAs: "a square, cut from a tray",
  },
  {
    printedName: "Paella valenciana",
    englishName: "Paella",
    aliases: ["paella", "paella valenciana", "seafood paella"],
    oneLine: "Saffron rice cooked flat in a wide pan until the bottom crisps.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "shellfish", likelihood: "usually", from: "the prawns and langoustines, in the seafood version" },
      { key: "molluscs", likelihood: "usually", from: "the mussels and clams, in the seafood version" },
      { key: "fish", likelihood: "sometimes", from: "the fish stock the rice is cooked in" },
    ],
    whatItIs:
      "Short rice spread thin in a wide flat pan and cooked without stirring in stock coloured with saffron, so the grains stay separate and a toasted crust forms underneath. The original is rabbit, chicken and beans; the seafood one is the tourist favourite.",
    tastesLike: "Savoury and faintly perfumed, with a chewy, almost burnt layer at the bottom that is the best part.",
    origin: "Valencia, Spain",
    madeWith: ["bomba rice", "saffron", "stock", "green beans", "chicken or seafood", "olive oil"],
    servedAs: "the pan itself, shared",
  },
  {
    printedName: "Tortilla española",
    englishName: "Spanish omelette",
    aliases: ["tortilla espanola", "tortilla de patatas", "spanish omelette", "spanish tortilla"],
    oneLine: "A thick cake of potato and egg, cooked slowly and cut in wedges.",
    priceText: "",
    course: "starters",
    dietary: "vegetarian",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "eggs", likelihood: "usually", from: "the eggs it is made of" },
    ],
    whatItIs:
      "Potatoes cooked gently in a lot of olive oil until soft but not brown, drained, mixed into beaten egg with onion, then set in a pan and flipped so both sides colour. It is meant to stay slightly loose in the middle.",
    tastesLike: "Plain in a good way — soft potato, rich egg, a lot of olive oil.",
    origin: "Spain",
    madeWith: ["potato", "eggs", "onion", "olive oil", "salt"],
    servedAs: "a wedge, warm or cold",
  },
  {
    printedName: "Cacio e pepe",
    englishName: "",
    aliases: ["cacio e pepe", "cacio pepe"],
    oneLine: "Pasta in a sauce of nothing but sheep's cheese, pepper and pasta water.",
    priceText: "",
    course: "mains",
    dietary: "vegetarian",
    spice: "mild",
    recognised: true,
    likelyAllergens: [
      { key: "gluten", likelihood: "usually", from: "the wheat pasta" },
      { key: "dairy", likelihood: "usually", from: "the pecorino cheese, which is the whole sauce" },
    ],
    whatItIs:
      "Tonnarelli or spaghetti cooked in very little water, then tossed off the heat with grated pecorino romano and a lot of cracked black pepper, using the starchy water to pull it into a cream. There is no butter and no oil.",
    tastesLike: "Sharp, salty and peppery. Simple and very strong.",
    origin: "Rome",
    madeWith: ["pasta", "pecorino romano", "black pepper", "pasta water"],
    servedAs: "a plate, eaten immediately",
  },
  {
    printedName: "Pesto alla genovese",
    englishName: "Pasta with pesto",
    aliases: ["pesto", "pesto alla genovese", "pasta pesto"],
    oneLine: "Pasta in a raw green sauce of basil, pine nuts, garlic and cheese.",
    priceText: "",
    course: "mains",
    dietary: "vegetarian",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "tree_nuts", likelihood: "usually", from: "the pine nuts crushed into the sauce" },
      { key: "dairy", likelihood: "usually", from: "the parmesan and pecorino" },
      { key: "gluten", likelihood: "usually", from: "the wheat pasta" },
    ],
    whatItIs:
      "Basil leaves crushed with garlic, pine nuts, coarse salt and olive oil, then beaten with grated parmesan and pecorino. It is never cooked — the heat of the pasta is all it gets.",
    tastesLike: "Bright and grassy from the basil, salty from the cheese, with a soft nuttiness.",
    origin: "Genoa, Liguria",
    madeWith: ["basil", "pine nuts", "garlic", "parmesan", "olive oil", "pasta"],
    servedAs: "a plate, often with potato and beans through it",
  },
  {
    printedName: "Bouillabaisse",
    englishName: "",
    aliases: ["bouillabaisse", "bouillabaise"],
    oneLine: "A big Provençal fish stew, the broth served first and the fish after.",
    priceText: "",
    course: "mains",
    dietary: "fish",
    spice: "mild",
    recognised: true,
    likelyAllergens: [
      { key: "fish", likelihood: "usually", from: "the several kinds of fish it is built on" },
      { key: "shellfish", likelihood: "usually", from: "the crab and langoustine in the broth" },
      { key: "molluscs", likelihood: "sometimes", from: "the mussels" },
      { key: "gluten", likelihood: "usually", from: "the toasted bread served with it" },
      { key: "eggs", likelihood: "usually", from: "the rouille, which is an egg-yolk mayonnaise" },
    ],
    whatItIs:
      "Several kinds of rocky Mediterranean fish simmered with saffron, fennel, tomato and orange peel. The broth is strained and served first with toasted bread and rouille, a garlicky red mayonnaise; the fish comes as a second course.",
    tastesLike: "Deeply of the sea, with saffron and orange lifting it.",
    origin: "Marseille",
    madeWith: ["rockfish", "saffron", "fennel", "tomato", "orange peel", "garlic"],
    servedAs: "two courses, from one pot",
  },
  {
    printedName: "Quiche lorraine",
    englishName: "",
    aliases: ["quiche lorraine", "quiche"],
    oneLine: "An open pastry case filled with bacon set in baked egg and cream.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "gluten", likelihood: "usually", from: "the pastry case" },
      { key: "eggs", likelihood: "usually", from: "the custard filling" },
      { key: "dairy", likelihood: "usually", from: "the cream, and the butter in the pastry" },
    ],
    whatItIs:
      "A shortcrust case blind-baked, filled with pieces of smoked bacon and a custard of egg, cream and nutmeg, then baked until it barely sets and puffs. The classic has no cheese in it at all.",
    tastesLike: "Soft, rich and smoky, with a crumbly base.",
    origin: "Lorraine, France",
    madeWith: ["shortcrust pastry", "bacon", "eggs", "cream", "nutmeg"],
    servedAs: "a wedge, warm",
  },
  {
    printedName: "ხაჭაპური",
    englishName: "Khachapuri",
    aliases: ["khachapuri", "hachapuri", "georgian cheese bread"],
    oneLine: "A boat of bread filled with molten cheese, with butter and an egg yolk on top.",
    priceText: "",
    course: "mains",
    dietary: "vegetarian",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "dairy", likelihood: "usually", from: "the cheese filling and the butter" },
      { key: "gluten", likelihood: "usually", from: "the bread" },
      { key: "eggs", likelihood: "usually", from: "the raw yolk dropped on top of the Adjarian one" },
    ],
    whatItIs:
      "Bread dough shaped into an open boat, filled with salty brined cheese and baked. The Adjarian version comes out with a raw egg yolk and a knob of butter dropped into the middle, which you stir through the hot cheese at the table and tear the crust off to dip.",
    tastesLike: "Salty, stretchy and enormously rich.",
    origin: "Georgia",
    madeWith: ["bread dough", "sulguni cheese", "butter", "egg yolk"],
    servedAs: "one boat, hot, per person",
  },
  {
    printedName: "Pierogi ruskie",
    englishName: "Potato and cheese dumplings",
    aliases: ["pierogi", "perogi", "pirogi", "pierogi ruskie"],
    oneLine: "Boiled dumplings filled with potato and curd cheese, with fried onion over them.",
    priceText: "",
    course: "mains",
    dietary: "vegetarian",
    spice: "none",
    recognised: true,
    likelyAllergens: [
      { key: "gluten", likelihood: "usually", from: "the wheat dough" },
      { key: "dairy", likelihood: "usually", from: "the curd cheese in the filling and the butter over the top" },
      { key: "eggs", likelihood: "sometimes", from: "the egg in the dough" },
    ],
    whatItIs:
      "Soft wheat dough rolled thin, cut in circles, filled with mashed potato and twaróg curd cheese, folded and pinched shut, then boiled and usually fried a little. Fried onion or bacon and sour cream go on top.",
    tastesLike: "Soft and plain and comforting, salty from the cheese and sweet from the onion.",
    origin: "Poland",
    madeWith: ["wheat flour", "potato", "twaróg cheese", "onion", "butter"],
    servedAs: "a plate of six or eight",
  },

  /* ---- The Americas and Africa ----------------------------------------- */
  {
    printedName: "Tacos al pastor",
    englishName: "",
    aliases: ["tacos al pastor", "al pastor", "tacos"],
    oneLine: "Pork off a vertical spit in small corn tortillas, with pineapple and coriander.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "medium",
    recognised: true,
    likelyAllergens: [
      { key: "gluten", likelihood: "sometimes", from: "the tortillas, if they are flour rather than corn" },
    ],
    whatItIs:
      "Pork marinated in dried chilli, achiote and vinegar, stacked on a vertical spit with a pineapple on top, shaved off as it cooks into small double corn tortillas with onion, coriander and a piece of the pineapple.",
    tastesLike: "Smoky, sour and slightly sweet, with the pineapple cutting the fat.",
    origin: "Mexico City, out of Lebanese shawarma",
    madeWith: ["pork", "achiote", "dried chilli", "pineapple", "corn tortillas", "coriander"],
    servedAs: "three or four small tacos",
  },
  {
    printedName: "Mole poblano",
    englishName: "Chicken in mole",
    aliases: ["mole", "mole poblano", "mole sauce"],
    oneLine: "Chicken under a near-black sauce of many chillies, nuts, seeds and chocolate.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "medium",
    recognised: true,
    likelyAllergens: [
      { key: "tree_nuts", likelihood: "usually", from: "the almonds ground into the sauce" },
      { key: "sesame", likelihood: "usually", from: "the sesame seeds in the sauce and scattered over" },
      { key: "peanuts", likelihood: "sometimes", from: "the peanuts some recipes use alongside the almonds" },
      { key: "gluten", likelihood: "sometimes", from: "the bread or crackers used to thicken it" },
    ],
    whatItIs:
      "Several kinds of dried chilli toasted and soaked, ground with almonds, sesame, raisins, spices, a little dark chocolate and stale bread, then cooked down for hours into a thick, almost black sauce and poured over poached chicken.",
    tastesLike: "Not chocolatey — deep, smoky, faintly bitter and sweet, with a slow heat.",
    origin: "Puebla, Mexico",
    madeWith: ["dried chillies", "almonds", "sesame seeds", "chocolate", "spices", "chicken"],
    servedAs: "a plate with rice and tortillas",
  },
  {
    printedName: "ዶሮ ወጥ",
    englishName: "Doro wat",
    aliases: ["doro wat", "doro wot", "ethiopian chicken stew"],
    oneLine: "A dark, fiery chicken stew eaten with sour flatbread instead of cutlery.",
    priceText: "",
    course: "mains",
    dietary: "meat",
    spice: "hot",
    recognised: true,
    likelyAllergens: [
      { key: "eggs", likelihood: "usually", from: "the boiled eggs cooked in the stew" },
      { key: "dairy", likelihood: "sometimes", from: "the spiced clarified butter it starts with" },
      { key: "gluten", likelihood: "sometimes", from: "the injera, if the teff is cut with wheat or barley" },
    ],
    whatItIs:
      "A great quantity of onion cooked down dry until it collapses, then built up with berbere chilli spice and spiced butter, and simmered with chicken and whole boiled eggs. It is scooped up with injera, a large sour pancake made from teff.",
    tastesLike: "Hot, deeply spiced and slightly sour from the bread underneath.",
    origin: "Ethiopia",
    madeWith: ["chicken", "onion", "berbere", "niter kibbeh", "boiled eggs", "injera"],
    servedAs: "poured onto a shared round of injera",
  },
];
